#!/bin/bash
# Финальный скрипт деплоя BALT-SET.RU

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚀 ДЕПЛОЙ BALT-SET.RU - УСЛУГИ ЭЛЕКТРИКА"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ ЧТО БУДЕТ ЗАДЕПЛОЕНО:"
echo "  1. 'Наши услуги' → 'Услуги электрика'"
echo "  2. Система скидок за объем (3/5/11/21+ шт)"
echo "  3. Кнопка '← К услугам' в корзине"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Проверяем архив
if [ ! -f "electric-service-automation-main.tar.gz" ]; then
    echo "📦 Создаю архив проекта..."
    tar -czf electric-service-automation-main.tar.gz electric-service-automation-main/
    echo "✅ Архив создан: $(ls -lh electric-service-automation-main.tar.gz | awk '{print $5}')"
else
    echo "✅ Архив найден: $(ls -lh electric-service-automation-main.tar.gz | awk '{print $5}')"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📤 КОПИРОВАНИЕ НА VPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "VPS: 176.98.178.109"
echo "Пароль: vfhufhbnrf"
echo ""
echo "⏳ Копирую архив на VPS..."
echo ""

scp electric-service-automation-main.tar.gz root@176.98.178.109:/tmp/

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Архив скопирован на VPS!"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  🔨 СБОРКА И УСТАНОВКА НА VPS"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Теперь выполните на VPS:"
    echo ""
    echo "ssh root@176.98.178.109"
    echo "# Пароль: vfhufhbnrf"
    echo ""
    echo "cd /tmp && \\"
    echo "tar -xzf electric-service-automation-main.tar.gz && \\"
    echo "cd electric-service-automation-main && \\"
    echo "npm install && \\"
    echo "npm run build && \\"
    echo "cp -r dist/* /var/www/app.balt-set.ru/ && \\"
    echo "chmod -R 755 /var/www/app.balt-set.ru/ && \\"
    echo "echo '✅ Готово! https://app.balt-set.ru/'"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "💡 АЛЬТЕРНАТИВА: Запустить всё автоматически"
    echo ""
    echo "ssh root@176.98.178.109 'cd /tmp && tar -xzf electric-service-automation-main.tar.gz && cd electric-service-automation-main && npm install && npm run build && cp -r dist/* /var/www/app.balt-set.ru/ && chmod -R 755 /var/www/app.balt-set.ru/'"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "🧪 ПОСЛЕ ДЕПЛОЯ ПРОВЕРЬТЕ:"
    echo ""
    echo "  1. Откройте https://app.balt-set.ru/"
    echo "  2. Найдите 'Услуги электрика' (было 'Наши услуги')"
    echo "  3. Добавьте 3 розетки - увидите скидку 5%"
    echo "  4. В корзине нажмите 'Редактировать'"
    echo "  5. Появится кнопка '← К услугам'"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "✅ ШАГ 1 ЗАВЕРШЕН: Архив на VPS"
    echo "➡️  ШАГ 2: Выполните команды выше на VPS"
    echo ""
else
    echo ""
    echo "❌ Ошибка копирования"
    echo ""
    echo "💡 Попробуйте вручную:"
    echo "   scp electric-service-automation-main.tar.gz root@176.98.178.109:/tmp/"
    echo "   Пароль: vfhufhbnrf"
    echo ""
fi
